### ISSUE TITLE
not working for test flight builds.

### ISSUE THREAD

**Issue by krina-pixster** [sindresorhus/LaunchAtLogin-Modern#1]
I have implement this in my app which is working correctly in the device in which I have created the app. I have tested this by exporting app in my device but as soon as I upload the same on ten flight and I download it in another device and the app is not restarting by it self in that device after login though it is showing in system preferences in login items

**Comment by sindresorhus** [comment]
That's not really an issue with this package then. If it shows in login items, this package has done its job. The actual launching of the app is handled by the system.

**Comment by miquellaboria** [comment]
@krina-pixster I have the same issue, my App on TestFlight doesn't open at launch... :(

But the same App out of TestFlight works perfectly...

Have you found some way to fix it?

Thanks!

**Comment by krina-pixster** [comment]
Hello,

No, I have not found any solution for this issue but it works perfectly
when it is live. so I have just ignored this issue
