### ISSUE TITLE
'mainApp' is only available in Mac Catalyst 16.0 or newer

### ISSUE THREAD

**Issue by tkafka** [sindresorhus/LaunchAtLogin-Modern#4]
Hello, if I want to use LaunchAtLogin in a catalyst app, it only seems possible since 16.0, otherwise there are build errors `'mainApp' is only available in Mac Catalyst 16.0 or newer`.

Could you please update Package.swift to reflect this (I don't have experience with authoring swift packages)?

**Comment by tkafka** [comment]
Hmm, the problem is mainly with the logger, which gets instantiated statically right at start, so no `if #available` can prevent it. In the end I took the source, removed the logger, and wrapped the uses of SMAppService, like this: https://gist.github.com/tkafka/d4e61cad23cad59ace5fd92f640001e6

**Comment by sindresorhus** [comment]
Can you check if it works if I add `.macCatalyst(.v16)` to https://github.com/sindresorhus/LaunchAtLogin-Modern/blob/9c41991631605c8ccfe0347bbcb5c659169f2ec5/Package.swift#L6-L8 ?
